type: signal
name: spec_64k

resampling:
  target_sampling_rate: 64000
  max_bandwidth_factor: 0.5

segmentation:
  window_duration: 0.05
  window_overlap: 0.2

view:
  type: stft
  n_fft: 256
  hop_length: 96
  win_length: 256