name: cnn1d_res_se
type: 1d

encoder:
  - [res, 1, 2, {k: 7, s: 1, blocks: 1, act: relu}]
  - [se, {r: 2}]
  - [pool, {k: 2, s: 2, p: 1}]
  - [dropout, 0.01]
  - [res, 2, 4, {k: 5, s: 1, blocks: 1, act: relu}]
  - [se, {r: 2}]
  - [pool, {k: 2, s: 2, p: 1}]
  - [dropout, 0.01]
  - [res, 4, 8, {k: 3, s: 1, blocks: 1, act: relu}]
  - [se, {r: 2}]
  - [pool, {k: 2, s: 2, p: 1}]

aggregator:
  type: multihead
  levels: [16,4,1]

head:
  depth: 2
  dropout: 0.1
  act: relu
