name: paderborn_reader
format: mat
loader: scipy
simplify_cells: true

channels:
  vibration:
    variable_name: vibration_1
    dtype: float32
  phase_current_1:
    variable_name: phase_current_1
    dtype: float32
  phase_current_2:
    variable_name: phase_current_2
    dtype: float32
  rpm:
    variable_name: speed
    dtype: float32
  torque:
    variable_name: torque
    dtype: float32
  force:
    variable_name: force
    dtype: float32

file_key:
  source: filename    # use Path(fname).stem directly
